### ISSUE TITLE
Bug when view of calendar changed 

### ISSUE THREAD

**Issue by rassimjhan** [schedule-x/schedule-x#320] opened 2024-04-01 10:21 UTC
**Context:**

- Browser Chrome
- Browser-version 123.0.6312.58 
- Schedule-X version: 
"@schedule-x/calendar": "^1.27.0",
"@schedule-x/shared": "^1.27.0",
"@schedule-x/theme-default": "^1.27.0",
"@schedule-x/vue": "^1.23.0

**Describe the bug**

**when error occured, i've got empty calendar**
![image](https://github.com/schedule-x/schedule-x/assets/63673193/15a9eacd-06c8-418e-a75f-c7bd429e70ef)
**here in devtools i found this**
![image](https://github.com/schedule-x/schedule-x/assets/63673193/5006bbda-562b-41fe-9bec-fde27dc320be)
![image](https://github.com/schedule-x/schedule-x/assets/63673193/4e4639fb-465b-4353-a6c9-05aae0f79ce6)

I think error occured when view of calendar changed to month or to another view

**also when i try to select day of month i got this**
<img width="424" alt="image" src="https://github.com/schedule-x/schedule-x/assets/63673193/ced02687-3a5e-44a2-906e-42f4f1ddb481">

**error in console**
<img width="908" alt="image" src="https://github.com/schedule-x/schedule-x/assets/63673193/f62c1d11-d869-4ed6-84c4-84d9242d9c47">

<img width="538" alt="image" src="https://github.com/schedule-x/schedule-x/assets/63673193/95951003-be46-4a1b-94d3-43a4d55038bb">

**To Reproduce**
```
// plugin to make calendars reactive

class CalendarsUpdaterPlugin {
  name: string = "calendars-updater"
  $app!: CalendarAppSingleton

  init($app: CalendarAppSingleton): void {
    this.$app = $app
    console.log("$app", this.$app)
    this.$app.config.calendars.value = {
      ...store.calendarBookings?.reduce(
        (acc, v) => ({
          ...acc,
          [v.id]: v.calendar,
        }),
        {}
      ),
    }
  }

// i tried use this function but output of this.$app is undefined
  updateCalendars(calendar: any): void {
    console.log("config", this.$app) // **output is undefined**
    console.log("calendar plugin", calendar)
    this.$app.config.calendars.value = {
      ...store.calendarBookings?.reduce(
        (acc, v) => ({
          ...acc,
          [v.id]: v.calendar,
        }),
        {}
      ),
    }
  }
}
```

```
const calendarApp = createCalendar({
  plugins: [new CalendarsUpdaterPlugin()],
  views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
  defaultView: viewWeek.name,
  locale: "ru-RU",

  calendars: {},
  events: [],
  dayBoundaries: {
    start: "07:00",
    end: "21:00",
  },
...
})

```

```
// update events
watch(
  () => store.calendarBookings,
  (newValue: any, oldValue: any) => {
    calendarApp.events.set(newValue)
  }
)
```

1. select view of calendar (month, week, day)
2. click on datepicker
3. doesn't display days of month

**Comment by tomosterlund** [comment] 2024-04-01 14:19
I think I'll need a minimal reproduction environment to help out here. I tried reproducing this in the vue-example repo: https://github.com/schedule-x/vue-example. But I didn't manage to replicate your error.

Could you please set up a minimal reproduction example in Stackblitz, GitHub repo or similar?

**Comment by rassimjhan** [comment] 2024-04-09 12:07
@tomosterlund I found solution for this issue. 
The problem was with plugin.

```const calendarApp = createCalendar({
  plugins: [new CalendarsUpdaterPlugin()],
  views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
  defaultView: viewWeek.name,
  locale: "ru-RU",

  calendars: {},
  events: [],
  dayBoundaries: {
    start: "07:00",
    end: "21:00",
  },
...
})

**Comment by lcarbow** [comment] 2024-04-11 09:02
i just read this Issue since i got the same error now setting this up. Unfortunately the fix doesnt work for me. On first page load, the calendars are added correctly, but when trying to fetch and update agein without reloading the page again, i get the this.$app is undefined error.

`import { CalendarAppSingleton } from '@schedule-x/shared'
class CalendarsUpdaterPlugin {
    name: string = 'calendars-updater'
    $app!: CalendarAppSingleton

    init($app: CalendarAppSingleton): void {
      this.$app = $app
    }

    updateCalendars(calendars: any): void {
      console.log('Updating calendars', calendars, this.$app);
      
      const updatedCalendars = { ...this.$app.config.calendars.value };

      Object.keys(calendars).forEach((calendarKey) => {
        updatedCalendars[calendarKey] = calendars[calendarKey];
      });
      this.$app.config.calendars.value = updatedCalendars;
    }
  }
  export default CalendarsUpdaterPlugin;`

Do you have any clue how to fix this?

**Comment by tomosterlund** [comment] 2024-04-15 15:14
I still need a minimal repro environment to work on this. If you can share one over for example Code Sandbox or similar, I can have a look

**Comment by tomosterlund** [comment] 2024-04-19 15:22
Closing this due to inability to reproduce. Feel free to open this issue again with a reproduction example

**Closed by tomosterlund** 2024-04-19 15:22 UTC
