### ISSUE TITLE
Agenda/List/Schedule view

### ISSUE THREAD

**Issue by nstringham** [schedule-x/schedule-x#633] opened 2024-09-02 14:45 UTC
**Is your feature request related to a problem? Please describe.**  
The day view and month agenda view are good for visualizing densely packed calendars with multiple events per day. However the are less ideal for displaying sparce calendars with one or 2 even per week.

**Describe the solution you'd like**  
I would like an agenda view like what Google calendar for Android calls "Schedule". It would look alot like the month agenda view except that instead of requiring the user to select a day and only rendering the events for that day it should render all the events. It should either load an entire month like FullCalendar's "list" view or be an infinite scroller like Google's "schedule" view.

**Additional context**  
I would like to migrate away from FullCalendar but I need a way for mobile users to better visualize our sparce events https://michigankendo.com/calendar

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by nstringham** [comment] 2024-09-02 17:27
Ope sorry I think this is probably a duplicate of #393 My bad.

**Comment by tomosterlund** [comment] 2024-09-02 19:13
Actually I’ve been thinking about trying to make this happen lately also 😊 I think an infinite scroll list sounds the most appealing and modern to me.

if you’re up for it, we could have a chat some day this or next week, and talk about how to implement it? Let me know if you’re up for it, and I’ll send you my calendly

**Comment by zalhabash** [comment] 2024-09-03 13:59
@tomosterlund Do you think I could join this meeting? @nstringham  is collaborating with/mentoring me through the project we're both working on. I am much less experienced, so I don't know much about implementing this feature, but I'm really excited to learn!

**Comment by tomosterlund** [comment] 2024-09-03 20:29
@zalhabash sure thing!

Maybe the two of you could have a look at [my calendly](https://calendly.com/schedule-x/lets-chat) and see if any of the time slots this week suit you. If none work, let me know and I'll add some for next week too

**Comment by tomosterlund** [comment] 2024-12-03 07:33
Closing since this is a duplicate of another issue

**Closed by tomosterlund** 2024-12-03 07:33 UTC
Labels: enhancement
