### ISSUE TITLE
Drag and Drop for custom Time Grid Event component - time does not update

### ISSUE THREAD

**Issue by CindyFMX** [schedule-x/schedule-x#558] opened 2024-07-26 04:27 UTC
Context:
- Browser: Chrome 
- Browser-version: Version 126.0.6478.183
- Schedule-X version: 
    "@schedule-x/drag-and-drop": "^1.54.0",
    "@schedule-x/vue": "^1.49.0",

Bug:
The time getting displayed on the calendar does not update if the event is dropped on the same day. Need to navigate to other view first then only it is updated.

**To Reproduce**

1. Create custom time grid event component
2. Display the calendarEvent.start
3. Drag the event displayed and drop it on the other time slot but within the same day

**Expected behavior**
The start time should be updated

**Screenshots**

![Screenshot 2024-07-26 122612](https://github.com/user-attachments/assets/c2a0dbb0-cdb5-42dc-96a0-497e684354d3)

**Comment by CindyFMX** [comment] 2024-07-26 04:37
The resize plugin also does not update directly the time getting displayed.

![image](https://github.com/user-attachments/assets/d63e470b-490a-4f71-bc26-51522cf0f185)

![image](https://github.com/user-attachments/assets/670c5b29-a5c1-42ff-a5aa-3e6d2dbd801c)

this is my code if you need to understand

**Comment by tomosterlund** [comment] 2024-07-26 06:18
I can't reproduce. In this video I'm also using the latest vue version. Are you maybe intercepting pointer events on your event?

https://github.com/user-attachments/assets/3c11e3c3-f537-49c6-aa8d-2b3152b2244c

**Comment by CindyFMX** [comment] 2024-07-26 06:53
wait the resize plugin is working. It's just that the start time does not updated directly. Let me show you video for clearer view.


https://github.com/user-attachments/assets/f9a90e47-9cc5-4128-a147-d6af5a8c24e6

You see the time does not directly updated.

**Comment by tomosterlund** [comment] 2024-07-29 04:50
This will be fixed in the next release :) 

Thanks for taking the time to report!

**Closed** 2024-07-29 04:50 UTC
Labels: bug

**Comment by CindyFMX** [comment] 2024-07-29 06:49
May i know when will be the next release? As I need it quite urgently

**Comment by CindyFMX** [comment] 2024-08-05 06:57
> Reference i

Is there a function to refresh the calendar only ? I think I might be able to utilize that to counter the bug as currently if i move to other view first then come back, the time is actually updated

**Comment by CindyFMX** [comment] 2024-08-05 06:58
> This will be fixed in the next release :)
> 
> Thanks for taking the time to report!

Is there a function to refresh the calendar only ? I think I might be able to utilize that to counter the bug as currently if i move to other view first then come back, the time is actually updated

**Comment by tomosterlund** [comment] 2024-08-05 09:00
This should be fixed if you update to the latest release

**Comment by CindyFMX** [comment] 2024-08-06 03:16
> This should be fixed if you update to the latest release . If it’s not, it’s because it was maybe only included in the last automated release which failed. Am on vacation until tomorrow, and can check then.
> 
> but meanwhile please check if you’re on the latest version

It is working already, thanks a lot

**Comment by tomosterlund** [comment] 2024-08-06 17:03
Great! Thanks for your feedback 😊
