### ISSUE TITLE
DragAndDropPlugin activates on right click

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#536] opened 2024-07-10 14:27 UTC
**Describe the bug**
When `DragAndDropPlugin` is added, clicking with right-click activates dragging, even for events with `disableDND: true`

**Comment by tomosterlund** [comment] 2024-07-12 04:04
I'm not sure I want to dive into detection of right clicks to prevent those from causing a drag and drop, _unless of course_  they trigger unwanted behavior like overriding `disableDND`. I couldn't reproduce the problem with having ignored `disableDND` though.

Could you share some more on this, or a repro?

**Comment by tomosterlund** [comment] 2024-07-19 16:43
Closing this, since I can't reproduce. Feel free to open a new issue with a minimal repro if the problem persists

**Closed by tomosterlund** 2024-07-19 16:43 UTC
Labels: needs reproduction env
