### ISSUE TITLE
Dropping event fires onClickDateTime on day view

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#497] opened 2024-06-21 14:16 UTC
**Context:**

- Browser chrome
- Browser-version 126.0.6478.62
- Schedule-X version 1.45.0

**Describe the bug**

Using the drag-and-drop plugin in day view fires `onEventUpdate` which is correct, but it also fires `onClickDateTime` when the release a mouse click out of a cloned (dragging) event. This could be achieved if you move the cursor fast so the cloned event is lagged.
This is a bug for me since I open my custom modal `onClickDateTime`, and it's unexpected to open the modal when dropping the event.

**To Reproduce**

1. Set a day view
2. Grab an event 
3. Start dragging it up or down fast
4. Make sure your cursor is out of the dragging event
5. Release mouse
6. See `onClickDateTime` is fired

**Expected behavior**

When dropping events only `onEventUpdate` should be called

**Comment by lcarbow** [comment] 2024-07-10 11:27
Actually the problem seems to continue. I set up a sandbox here:

[](https://stackblitz.com/edit/vitejs-vite-nyzfa3?file=src%2FApp.tsx)

Looking at the console output it appears on release of drag, the callback still is fired. Maybe you can have a look on this again. Might be due to the react component?

![schedule-x](https://github.com/schedule-x/schedule-x/assets/82658493/b4e4f8ca-4eb2-4bde-9cc6-480ae62d13ce)

**Comment by tomosterlund** [comment] 2024-07-12 03:46
Hm, even though I'm using the same reproduction example, I can't reproduce this.

Which browser are you in, and how exactly are you moving those events? (I don't see any cursor)

**Comment by lcarbow** [comment] 2024-07-12 09:49
I'm using latest Firefox version. Moving is quite the simplest i can do, click and hold, drag, release. No hectic or fast cursor movements at all.

**Comment by tomosterlund** [comment] 2024-07-12 12:27
Hm. In Chrome and Safari this doesn't happen. I need to look into this further

**Comment by tomosterlund** [comment] 2024-07-19 16:38
Solved this for Firefox now too. Firefox seems to implement a different order than Chrome and Safari, in how different mouse events propagate.

The fix will be included in the next release

**Closed** 2024-07-19 16:39 UTC
Labels: bug
