### ISSUE TITLE
The calendar breaks and disappear when switching to month-grid for the second time

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#492] opened 2024-06-19 07:53 UTC
**Context:**

- Browser chrome
- Browser-version 125.0.6422.142 
- Schedule-X version 1.45.0 

**Describe the bug**

The calendar breaks and disappears and an error in the console appears:

**To Reproduce**

1. Set week as the default view
2. Change view to month-grid
3. Change to the day view 
4. Change to the month-grid view again

**Expected behavior**

Should not break or disappear when changing views

**Screenshots**

<img width="647" alt="image" src="https://github.com/schedule-x/schedule-x/assets/38419355/908b546c-7123-4ce5-a14a-cdcd8c002328">
<img width="501" alt="image" src="https://github.com/schedule-x/schedule-x/assets/38419355/837fda8c-3c91-42b6-87bb-0ef4512f3c16">

**Comment by tomosterlund** [comment] 2024-06-19 08:51
I can't reproduce. Can you please share your config?

**Comment by vukadinFE** [comment] 2024-06-19 08:58
> I can't reproduce. Can you please share your config?

Sure
```
import { ScheduleXCalendar } from "@schedule-x/vue";
import {
  createCalendar,
  viewDay,
  viewWeek,
  viewMonthGrid,
  viewMonthAgenda,
  type CalendarConfig,
} from "@schedule-x/calendar";
import "@schedule-x/theme-default/dist/index.css";
import { createEventModalPlugin } from "@schedule-x/event-modal";
import { createDragAndDropPlugin } from "@schedule-x/drag-and-drop";
import { createCalendarControlsPlugin } from "@schedule-x/calendar-controls";
import { createEventsServicePlugin } from "@schedule-x/events-service";
import { CalendarViewName } from "./enums";

type Emits = {
  (e: "view", value: CalendarViewName): void;
  (e: "dateRange", range: DateRange): void;
  (e: "date", date: string): void;
};

const emit = defineEmits<Emits>();

type Props = {
  view: CalendarViewName;
  views: [CalendarViewName, ...CalendarViewName[]];
};

const props = defineProps<Props>();

// Do not use a ref here, as the calendar instance is not reactive, and doing so might cause issues
// For updating events, use the events service plugin

const calendarControls = createCalendarControlsPlugin();
const eventsServicePlugin = createEventsServicePlugin();

const views = props.views.map((view) => {
  switch (view) {
    case "day":
      return viewDay;
    case "week":
      return viewWeek;
    case "month-grid":
      return viewMonthGrid;
    case "month-agenda":
    default:
      return viewMonthAgenda;
  }
}) as CalendarConfig["views"];



const calendarApp = createCalendar({
  plugins: [
    createEventModalPlugin(),
    createDragAndDropPlugin(),
    calendarControls,
    eventsServicePlugin,
  ],
  views: views,
  defaultView: props.view,
  callbacks: {
    /**
     * Is called when:
     * 1. Selecting a date in the date picker
     * 2. Selecting a new view
     * */
    onRangeUpdate(range) {
      console.log("new calendar range start date", range.start);
      console.log("new calendar range end date", range.end);

      console.log("view", calendarControls.getView());
      emit("view", calendarControls.getView() as CalendarViewName);
      emit("date", calendarControls.getDate());
      emit("dateRange", range);
    },

    /**
     * Is called when an event is updated through drag and drop
     * */
    onEventUpdate(updatedEvent) {
      console.log("onEventUpdate", updatedEvent);
    },

    /**
     * Is called when an event is clicked
     * */
    onEventClick(calendarEvent) {
      console.log("onEventClick", calendarEvent);
    },

    /**
     * Is called when clicking a date in the month grid
     * */
    onClickDate(date) {
      console.log("onClickDate", date); // e.g. 2024-01-01
      onNewTask();
    },

    /**
     * Is called when clicking somewhere in the time grid of a week or day view
     * */
    onClickDateTime(dateTime) {
      console.log("onClickDateTime", dateTime); // e.g. 2024-01-01 12:37
    },

    /**
     * Is called when clicking the "+ N events" button of a month grid-day
     * */
    onClickPlusEvents(date) {
      console.log("onClickPlusEvents", date); // e.g. 2024-01-01
    },

    /**
     * Is called when the selected date is updated
     * */
    onSelectedDateUpdate(date) {
      console.log("onSelectedDateUpdate", date);
    },
  },
});
```

**Comment by tomosterlund** [comment] 2024-06-19 09:26
2 things you could try:

1) import views in this file directly from '@schedule-x/calendar' instead of props and add them in the views config.
2) comment out your defaultView property.

One suspicion of mine, is that schedule-x does not yet work well with adding configuration through Vue props or `ref`, since these are reactive proxies, instead of the exact objects that schedule-x expects.

**Comment by vukadinFE** [comment] 2024-06-22 10:22
@tomosterlund Well I tried your proposal and the bug persists.
I peeked into the lib code and  `useEffect` in this file (`packages/calendar/src/views/week/components/week-wrapper.tsx`) seems to fire when the month view is selected a second time.

<img width="615" alt="image" src="https://github.com/schedule-x/schedule-x/assets/38419355/6231dbbc-2def-440a-b644-c73eb5928833">

**Comment by tomosterlund** [comment] 2024-06-24 08:36
I still can't reproduce this.

Please set up a minimal reproduction environment if you still need help with this. With many problems, that also helps spot where the error is, if the error is in the configuration.

**Comment by tomosterlund** [comment] 2024-06-29 09:49
Might have been resolved for you in the latest version. I suspect that you might have experienced the same race condition as mentioned in this issue: https://github.com/schedule-x/schedule-x/issues/503

Closing this issue, but feel free to open a new one with a repro if your problem would persist

**Comment by vukadinFE** [comment] 2024-07-01 16:11
It's fixed. Thank you

**Comment by vukadinFE** [comment] 2024-08-07 18:48
Hey @tomosterlund, I am facing this issue again in Vue.

**Month-Grid** default as view:
1. Load the page to get the range
2. Use range to fetch the data
3. After data is fetched save it to cache and use it to set it with `eventsServicePlugin.set()`
4. Change the view to the week or day
5. Triggers `onRangeUpdate` and use it to fetch new data
6. Same thing as **3.**
7. Change the view back to month-grid
8. Same as **5.**
9. Same thing as **3.** and **6.** but this time it is instant since the data is available in the cache because the range is the same as we got from **2.**

So the error (undefined in TimeGridEvents) happens after step **9.**

Maybe if you want to reproduce it, you could use a Tanstack query that has cache in place out of the box https://tanstack.com/query/latest/docs/framework/vue/guides/queries

Wrapping `eventsServicePlugin.set()` in `setTimeout` solves my issue, but I'd rather avoid such hackish solutions.

For the record, I am not using any reactive wrappers for calendar instances or plugins.

**Comment by tomosterlund** [comment] 2024-08-08 07:00
Thanks for the repro 💪  Now I can reproduce also on my local machine

**Closed** 2024-08-09 15:13 UTC
Labels: bug
