### ISSUE TITLE
setDate

### ISSUE THREAD

**Issue by Calmway** [schedule-x/schedule-x#470] opened 2024-06-07 05:49 UTC
Hello everyone. Here is my problem or bug that i want to ask.
I'm using Vue3+TS+Composition api

import { ScheduleXCalendar } from '@schedule-x/vue'
import { createCalendar, viewMonthGrid, viewWeek } from '@schedule-x/calendar'
import { createCalendarControlsPlugin } from '@schedule-x/calendar-controls';

const calendarControls = createCalendarControlsPlugin();
const calendarApp = ref(createCalendar({
      selectedDate: moment(today.value).format('YYYY-MM-DD'),
      views: [viewWeek, viewMonthGrid],
      defaultView: viewMonthGrid.name,
      firstDayOfWeek: 0,
      monthGridOptions: {
          nEventsPerDay: 88
      },
      dayBoundaries: {
          start: '08:00',
          end: '04:00',
      },
  ... and other stuff});

i have custom button that changes view (week or month)
have custom arrows that changes month in month view and should change week in week view, but:
1. i found that to change week we have to put first day of next or past week
2. calculating correct these dates:
//NOW 2024-06-07 and first day of next week is **2024-06-10**
3. today.value = "2024-06-10"
    calendarControls.setDate(moment(today.value).format('YYYY-MM-DD'));
but it doesn't change week but calendarControls.getDate() shows = 2024-06-10

by default is month view, and eveyrthing works fine there but not in week view
![image](https://github.com/schedule-x/schedule-x/assets/35524091/2459a5b1-20e3-4d3c-bc2d-b7eb5819cfc4)

**Comment by tomosterlund** [comment] 2024-06-07 12:24
I can't reproduce this. If you set up a reproduction environment I'll gladly look into it again though.

https://github.com/schedule-x/schedule-x/assets/63011648/bf440155-29fc-438f-8e71-ff5de7312e00

Your custom events look cool though!

**Comment by tomosterlund** [comment] 2024-06-15 06:26
I’ll go ahead and assume that this was fixed by this commit: https://github.com/schedule-x/schedule-x/commit/2fb2f71f993bce04915cad2a0a355a4bde3847d9

if your problem persists even when upgrading though, please open an issue again

**Closed by tomosterlund** 2024-06-15 06:26 UTC
Labels: needs reproduction env

**Comment by Calmway** [comment] 2024-07-16 12:54
https://github.com/user-attachments/assets/515949e2-9be0-4568-9a64-82c2c2bedb39

Hello. I'm using:

    "@schedule-x/calendar": "^1.51.0",
    "@schedule-x/calendar-controls": "^1.51.0",
    "@schedule-x/drag-and-drop": "^1.51.0",
    "@schedule-x/event-modal": "^1.51.0",
    "@schedule-x/events-service": "^1.51.0",
    "@schedule-x/theme-default": "^1.51.0",
    "@schedule-x/vue": "^1.47.0",
    
    
there is some problem with setDate i guess. As you can see on video it is schedule-x components (calendar, tools to change dates and so on, i didnt overwrite them)
Can you check it please :))))
Thank you in advance

**Comment by tomosterlund** [comment] 2024-07-17 04:45
I don't think this is a problem with `setDate`.

The problem is this line:

`const calendarApp = ref(createCalendar({`

You can't save the calendar in a ref; the calendar is not a mutable or reactive object. But I'm a bit surprised you don't get a TS-error for doing so. Do you have "strict" flag enabled in your tsconfig?

**Comment by Calmway** [comment] 2024-07-17 08:39
now everything is fine. thank you ❤️
